import type { CalculatorPreset } from './calculator';

// Data provenance:
// - Production: AER clearwater_bluesky_feb2026_prod_imperial.csv (Feb 2026)
// - Financials: Latest public corporate reports (Q4/FY2025 results, 2026 guidance)
// - WCS pricing: WTI $98.23 USD − $14.00 USD differential = $84.23 USD × 1.3716 = C$115.53/bbl
// - All prices in Canadian dollars (C$)
// - WellFi uplift: Average of estimated uplift observed across existing installations
// - Run-life extension: Calculated, varies by operator and use case

export const presets: CalculatorPreset[] = [
  {
    id: 'operator-a',
    label: 'Operator A',
    formation: 'Clearwater / Bluesky',
    companySummary: '414 wells — Clearwater & Bluesky producer',
    candidateWellCount: 414,
    topTierWellCount: 41,
    avgOilRatePerWellBpd: 23.34,
    topTierAvgOilRatePerWellBpd: 94.0,
    wellfiCostPerWellCad: 20_000,
    productionUpliftPct: 10,
    currentRunLifeMonths: 15,
    runLifeExtensionPct: 25,
    workoverCostPerEventCad: 50_000,
    netbackMode: 'direct',
    operatingNetbackCadPerBbl: 78.19,
    realizedOilPriceCadPerBbl: 115.53,
    royaltyRatePct: 15,
    variableOperatingCostCadPerBbl: 13.84,
    transportCostCadPerBbl: 3.44,
    gAndACostCadPerBbl: 2.73,
    drillRateMode: 'average',
    drillCapexPerWellCad: 2_900_000,
    drillYear1AvgBpd: 108.75,
    drillIp30Bpd: 150,
    drillFirstYearDeclinePct: 55,
    notes: [
      'Production: AER Feb 2026 filing',
      'Financials: Q4/FY2025 results, March 2026 corporate presentation',
      'WCS: C$115.53/bbl (WTI $98.23 USD − $14 diff × 1.3716 FX)',
    ],
  },
  {
    id: 'operator-b',
    label: 'Operator B',
    formation: 'Clearwater',
    companySummary: '264 wells — Clearwater producer',
    candidateWellCount: 264,
    topTierWellCount: 26,
    avgOilRatePerWellBpd: 66.57,
    topTierAvgOilRatePerWellBpd: 207.7,
    wellfiCostPerWellCad: 20_000,
    productionUpliftPct: 10,
    currentRunLifeMonths: 15,
    runLifeExtensionPct: 25,
    workoverCostPerEventCad: 50_000,
    netbackMode: 'direct',
    operatingNetbackCadPerBbl: 79.91,
    realizedOilPriceCadPerBbl: 115.53,
    royaltyRatePct: 17.2,
    variableOperatingCostCadPerBbl: 9.90,
    transportCostCadPerBbl: 4.25,
    gAndACostCadPerBbl: 1.60,
    drillRateMode: 'average',
    drillCapexPerWellCad: 2_000_000,
    drillYear1AvgBpd: 187.5,
    drillIp30Bpd: 250,
    drillFirstYearDeclinePct: 50,
    notes: [
      'Production: AER Feb 2026 filing',
      'Financials: 2026 guidance, estimated D&C from dev capex / well count',
      'WCS: C$115.53/bbl (WTI $98.23 USD − $14 diff × 1.3716 FX)',
    ],
  },
  {
    id: 'operator-c',
    label: 'Operator C',
    formation: 'Clearwater',
    companySummary: '657 wells — Clearwater producer',
    candidateWellCount: 657,
    topTierWellCount: 65,
    avgOilRatePerWellBpd: 71.09,
    topTierAvgOilRatePerWellBpd: 229.6,
    wellfiCostPerWellCad: 20_000,
    productionUpliftPct: 10,
    currentRunLifeMonths: 15,
    runLifeExtensionPct: 25,
    workoverCostPerEventCad: 50_000,
    netbackMode: 'direct',
    operatingNetbackCadPerBbl: 85.57,
    realizedOilPriceCadPerBbl: 115.53,
    royaltyRatePct: 15,
    variableOperatingCostCadPerBbl: 7.00,
    transportCostCadPerBbl: 4.25,
    gAndACostCadPerBbl: 1.38,
    drillRateMode: 'average',
    drillCapexPerWellCad: 1_900_000,
    drillYear1AvgBpd: 150,
    drillIp30Bpd: 200,
    drillFirstYearDeclinePct: 50,
    notes: [
      'Production: AER Feb 2026 filing',
      'Financials: 2026 guidance, D&C estimated from capex allocation',
      'WCS: C$115.53/bbl (WTI $98.23 USD − $14 diff × 1.3716 FX)',
    ],
  },
  {
    id: 'operator-d',
    label: 'Operator D',
    formation: 'Clearwater / Bluesky',
    companySummary: '178 wells — Clearwater & Bluesky producer',
    candidateWellCount: 178,
    topTierWellCount: 17,
    avgOilRatePerWellBpd: 38.33,
    topTierAvgOilRatePerWellBpd: 144.9,
    wellfiCostPerWellCad: 20_000,
    productionUpliftPct: 10,
    currentRunLifeMonths: 15,
    runLifeExtensionPct: 25,
    workoverCostPerEventCad: 60_000,
    netbackMode: 'direct',
    operatingNetbackCadPerBbl: 78.75,
    realizedOilPriceCadPerBbl: 115.53,
    royaltyRatePct: 15,
    variableOperatingCostCadPerBbl: 17.40,
    transportCostCadPerBbl: 0,
    gAndACostCadPerBbl: 2.05,
    drillRateMode: 'average',
    drillCapexPerWellCad: 3_100_000,
    drillYear1AvgBpd: 192.5,
    drillIp30Bpd: 275,
    drillFirstYearDeclinePct: 60,
    notes: [
      'Production: AER Feb 2026 filing',
      'Financials: H2 2025 guidance, D&C from dev capex / well count',
      'Transport bundled into opex — transport field set to zero',
      'WCS: C$115.53/bbl (WTI $98.23 USD − $14 diff × 1.3716 FX)',
    ],
  },
];
